version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
        - ./db:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SYSC3010-Lab-3

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: SYSC3010-Lab-3